// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Feed struct {
	ID        int64
	CreatedAt int64
	UpdatedAt int64
	Name      sql.NullString
	Url       string
}
